micronaut:
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:8080
  application:
    name: complete
#tag::application[]
application:
  max: 50
#end::application[]
#tag::datasource[]
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#end::datasource[]
#tag::jpa[]
jpa:
  default:
    packages-to-scan:
      - 'micronaut.turnos.domain' # <1>
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
#end::jpa[]